#!/usr/bin/env php
<?php

use BitbucketReviews\Command\Run;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    $autoloaderPath = __DIR__.'/vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    $autoloaderPath = __DIR__ . '/../../autoload.php';
}

require_once $autoloaderPath;

$application = new Application();

$application->add(new Run('run'));
$application->run();
