#!/usr/bin/env php
<?php

use BitbucketReviews\Command\Run;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$application = new Application();

$application->add(new Run('run'));
$application->run();
